#!/bin/sh

# stop - Stop a Debian chroot
# This file is part of android-debian-chroot-scripts
# Copyright (C) 2014  Andrea Bolognani <eof@kiyuko.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

die() {
	echo "$@" >&2
	cleanup
	exit 1
}

cleanup() {
	true
}

checkcommands() {                               
	type mktemp >/dev/null 2>&1 || {        
		die "mktemp: Command not found" 
	}
	type chroot >/dev/null 2>&1 || {        
		die "chroot: Command not found" 
	}
}

isrunning() {
	typeset end="/.root/$NAME"
	typeset -R"${#end}" tmp
	typeset f=$(mktemp)
	let rc=1
	
	df >"$f"
	while read fs _
	do
		tmp=$fs
		test "$tmp" = "$end" && {
			let rc=0
			break
		}
	done <"$f"
	rm -f "$f"
	
	return $rc
}

teardown() {
	umount "$ROOT/sys" || {
		die "Unable to umount $ROOT/sys"
	}
	umount "$ROOT/proc" || {
		die "Unable to umount $ROOT/proc"
	}
	umount "$ROOT/dev/pts" || {
		die "Unable to umount $ROOT/dev/pts"
	}
	umount "$ROOT/dev" || {
		die "Unable to umount $ROOT/dev"
	}
	umount "$ROOT" || {
		die "Unable to umount image"
	}
}

main() {                                                                
	BASE=$(dirname "$0")                                            
	NAME=${1:-default}
	ROOT="$BASE/.root/$NAME"
	IMAGE="$BASE/images/$NAME.img"

	test "$(whoami)" = root || {                                    
		die "Must be run as root"                               
	}                                                               

	checkcommands

	isrunning || {
		die "Not running"
	}

	chroot "$ROOT" /bin/sh -c \
		"export PATH=/usr/sbin:/usr/bin:/sbin:/bin;
		 test -f /etc/init.d/ssh && /etc/init.d/ssh stop;
		 sync"

	teardown

	exit 0
}

main "$@"
